#!/usr/bin/env python3
from sys import argv
from math import sqrt


def open_nd_read_file(file_name):
    """Read the numbers from
    file and add to array
    """
    with open(file_name, encoding="utf=8") as file:
        lines = file.readlines()
    number_2b_factor = []
    for line in lines:
        number_2b_factor.append(int(line))
    return number_2b_factor


def find_nd_times(n):
    """factor each
    given number n
    """
    for p in range(2, n):
        if(n % p == 0):
            print("{}={}*{}".format(n, (n/p), p))
            break


def factor_nd_list(ls):
    """factor each number
    and list
    """
    for p in ls:
        find_nd_times(p)


if len(argv) == 2:
    factor_nd_list(open_nd_read_file(argv[1]))
